apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-pods
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - flink
  selector:
    matchLabels:
      app: sql-dashboard
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: order-generator
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - orders
  selector:
    matchLabels:
      app: order-generator
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
