apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orders

resources:
  - order-generator-deployment.yaml
  - dashboard-backend-deployment.yaml
  - dashboard-frontend-deployment.yaml
  - timescaledb-statefulset.yaml
  - services.yaml
  - hpa.yaml
  - secret-provider-class.yaml
  - ingress.yaml
